### ISSUE TITLE
Cannot find namespace 'fb'

### ISSUE THREAD

**Issue by Drelaky** [SkyZeroZx/ngx-facebook-messenger#1]
Hello i install your package and dont work.

my error:
Error: node_modules/ngx-facebook-messenger/lib/ngx-facebook-messenger.component.d.ts:9:19 - error TS2503: Cannot find namespace 'fb'.

9     fbInitParams: fb.InitParams;
                    ~~
× Failed to compile.

but why?

**Comment by SkyZeroZx** [comment]
Hello
What version of the Angular currently use ? 
You are configure the init params required ? 
The error is when compiled the aplication or when clicked the ngx facebook button in develop server ? 
Can you give an example of the code you are using?

In develop server because is localhost and it's impossible register in the white list of facebook is normal the error of undefined fb

**Comment by SkyZeroZx** [comment]
Update 
Currently create a new proyect of Angular ( 16.XX) and throw the same error , because the @types of facebook , today update and fixed the typed 
Temporally it's possible install manual the types  npm i @types/facebook-js-sdk and should be working correctly 

If exist other error tell me

**Comment by Drelaky** [comment]
Hello please wait, i install the '@types/facebook-js-sdk'. my angular version: 16.2.3
and i use the html:
<ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' }" [ngxFacebookMessengerOptions]="{ page_id: 'ID'}"></ngx-facebook-messenger>

And i import the app.module.ts:
NgxFacebookMessengerModule

**Comment by SkyZeroZx** [comment]
Yes should be working , in my proyect where born the library currently install the   '@types/facebook-js-sdk'.
In pair of hours update the library and fixed the error

**Comment by Drelaky** [comment]
My error in command:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/b88389c4-f1cd-4524-9dd8-e38b660d8f94)

this error:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/98c5ea92-b5be-4c56-aeb1-a1741a3bc2c0)


sry but if i remove NgxFacebookMessengerModule in app.module.ts the ng serve success.

**Comment by Drelaky** [comment]
And i install:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/d3a3c190-8174-430f-b7c3-d58832c3e65f)

**Comment by SkyZeroZx** [comment]
I have a error because the typed not add when compiled the library change this line by the @types of facebook
and working complied , in pair of hours i update the library and fixed the current error
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/5415fccc-9063-439f-b652-8aa9c5247abd)

**Comment by Drelaky** [comment]
Thanks for the quick information!

**Comment by SkyZeroZx** [comment]
tell me if throw a other error and thanks for using the library.

**Comment by SkyZeroZx** [comment]
@Drelaky Currently update and fixed the library and working how expected.
New Version Fixed is 01.01.
Tell me if throw error or not , for close this isuue .

Commit fixed : d6f271b3c588e5cc4b7469abaf8a96c6631bf1c4

**Comment by Drelaky** [comment]
@SkyZeroZx  Yeah good but next problem:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/986d2b70-e64e-42fa-95b5-f1a06a30c81f)

The problem is that when I load the website, it returns with an error when I click on the logo first. Then it fixes the second time. Am I screwing something up? Please have a look yourself. And the custom css dont work.
my web: https://ligetnails.hu/

My code:
app.module.ts:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/98f0a2c0-c12c-4429-8520-5c7024c93995)

my component:
`<ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' }" [ngxFacebookMessengerOptions]="{ page_id: ID, }"></ngx-facebook-messenger>`


style.scss:
`#ngx-facebook-messenger {
  .wrapper {
    background: $rose !important;
  }
}`

**Comment by Drelaky** [comment]
You can also find the bug on the demo page.

![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/07a425db-b9e2-42f5-9d96-61d5021c20da)

**Comment by Drelaky** [comment]
Or is there some way to set a different language? Is it supported by api?

**Comment by SkyZeroZx** [comment]
> You can also find the bug on the demo page.
> 
> ![image](https://user-images.githubusercontent.com/53569746/278495707-07a425db-b9e2-42f5-9d96-61d5021c20da.png)

This error is "normal" because currently in Facebook Messenger Plugin  "happens" , why ? i don't know but currently working correctly the plugin or not ? in my case working

**Comment by SkyZeroZx** [comment]
> Or is there some way to set a different language? Is it supported by api?

I didn't understand what language, could you explain to me?

Your question it's for this URL ?

In my case in LATAM Facebook page give me that next URL  , Which I think is generic or am I wrong?

![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/5c521e1d-4fcf-4111-b2f9-c854853874f4)

**Comment by SkyZeroZx** [comment]
> @SkyZeroZx Yeah good but next problem: ![image](https://user-images.githubusercontent.com/53569746/278494346-986d2b70-e64e-42fa-95b5-f1a06a30c81f.png)
> 
> The problem is that when I load the website, it returns with an error when I click on the logo first. Then it fixes the second time. Am I screwing something up? Please have a look yourself. And the custom css dont work. my web: https://ligetnails.hu/
> 
> My code: app.module.ts: ![image](https://user-images.githubusercontent.com/53569746/278494636-98f0a2c0-c12c-4429-8520-5c7024c93995.png)
> 
> my component: `<ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' }" [ngxFacebookMessengerOptions]="{ page_id: ID, }"></ngx-facebook-messenger>`
> 
> style.scss: `#ngx-facebook-messenger { .wrapper { background: $rose !important; } }`

I already mentioned the first error that it is normal that it currently occurs for some reason that Facebook does not review.
Regarding the CSS, let me review it and I'll tell you.

**Comment by SkyZeroZx** [comment]
@Drelaky 
Update about the error in CSS is documentation error  in view "ICON"
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/db17a8b1-8c10-4daf-99d8-a55e91ed9fcd)
Configure how the next image 
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/d3685d97-685d-4e65-a64b-5076bf37bb41)
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/5a219287-11f2-43ad-a8e1-ffd3edd26d95)




If your use styles in style.css not is necesary "important" 

if use in component should be important because don't work for the view encapsulation what use Angular in the component.

In pair of hours update the Readme with the correct configuration , if happen other error tell me

**Comment by Drelaky** [comment]
> > Vagy van valami mód más nyelv beállítására? Támogatja az api?
> 
> Nem értettem milyen nyelven, elmagyaráznád nekem?
> 
> A kérdésed erre az URL-re vonatkozik?
> 
> Az én esetemben a LATAM Facebook oldalon adja meg a következő URL-t , szerintem általános, vagy tévedek?
> 
> ![kép](https://user-images.githubusercontent.com/73321943/278504762-5c521e1d-4fcf-4111-b2f9-c854853874f4.png)

Yes, can en-US be exchanged for, say, hu-HU or something else? Does that work? To make the texts appear in another language?

**Comment by SkyZeroZx** [comment]
> > > Vagy van valami mód más nyelv beállítására? Támogatja az api?
> > 
> > 
> > Nem értettem milyen nyelven, elmagyaráznád nekem?
> > A kérdésed erre az URL-re vonatkozik?
> > Az én esetemben a LATAM Facebook oldalon adja meg a következő URL-t , szerintem általános, vagy tévedek?
> > ![kép](https://user-images.githubusercontent.com/73321943/278504762-5c521e1d-4fcf-4111-b2f9-c854853874f4.png)
> 
> Yes, can en-US be exchanged for, say, hu-HU or something else? Does that work? To make the texts appear in another language?

Possible but I don't know if is possible with the URL, but if is possible and how configurable parameter .
Although I would ask you a favor, when you get the Facebook URL plugin in your region, what does it give you to take into account if that is

**Comment by Drelaky** [comment]
In truth, the only good thing about this change of region would be that the texts would be displayed in the language. There is a similar package I used to use called the 'ngx-facebook' module. However, it no longer supports angular 16. There you had to integrate the api into the index.html. Then import it into the app.module. I don't know exactly how it worked back then. But there was no render bug or anything like that. I know it's purely a different module that you make and I'm perfectly happy with it that way too. There is an alternative that works. Maybe you can draw something from that. Of course, proceed with care and caution, because code base is not up to date.

**Comment by Drelaky** [comment]
Hmmmm i try use index.html the original facebook api, and work. my code: 
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/0974074a-0c02-4df7-8708-0fa71f67acde)

**Comment by SkyZeroZx** [comment]
> In truth, the only good thing about this change of region would be that the texts would be displayed in the language. There is a similar package I used to use called the 'ngx-facebook' module. However, it no longer supports angular 16. There you had to integrate the api into the index.html. Then import it into the app.module. I don't know exactly how it worked back then. But there was no render bug or anything like that. I know it's purely a different module that you make and I'm perfectly happy with it that way too. There is an alternative that works. Maybe you can draw something from that. Of course, proceed with care and caution, because code base is not up to date.

@Drelaky 
I understand the language and url more , today add this flag for configure language or url , in your experience what form is better for you ? 
add parameter to replace complete original URL o only string for indicate region how ES_en , hu_HU.
And about the bug of render , this library have a bug of render ? it's the error in console for facebook in last comments or other ? 

First option
<ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' }" [ngxFacebookMessengerOptions]="{ page_id: 'YOUR_PAGE_ID' , language : 'Es_en' }"> </ngx-facebook-messenger>

Or
<ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' , language : 'Es_en'  }" [ngxFacebookMessengerOptions]="{ page_id: 'YOUR_PAGE_ID' , url  : 'YOUR_NEW_URL_SDK' }"> </ngx-facebook-messenger>

**Comment by SkyZeroZx** [comment]
> Hmmmm i try use index.html the original facebook api, and work. my code: ![image](https://user-images.githubusercontent.com/53569746/278780033-0974074a-0c02-4df7-8708-0fa71f67acde.png)

Yes API native of facebook work correctly but "killed" your web vitals and more complex used method of SDK Facebook.
In case this library is a wrapper lightweight for interactive with the SDK  

Add evidence of comparative of performance 

Before
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/a8eb81b6-7fd2-41d6-b13c-88b3b4a13aa2)

After of Ngx Facebook Messenger
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/95999dbb-39d8-40e3-b7fa-77b77b671276)

**Comment by Drelaky** [comment]
> > Valójában az egyetlen jó dolog ebben a régióváltásban az lenne, hogy a szövegek a nyelven jelennének meg. Van egy hasonló csomag, amit korábban használtam, 'ngx-facebook' modul néven. Viszont az angular 16-ot már nem támogatja. Ott kellett integrálni az API-t az index.html-be. Ezután importálja az app.module-ba. Nem tudom pontosan, hogyan működött akkor. De nem volt renderelési hiba vagy ilyesmi. Tudom, hogy ez egy teljesen más modul, amit te készítesz, és így is tökéletesen elégedett vagyok vele. Van egy alternatíva, ami működik. Talán ebből meríthetsz valamit. Természetesen óvatosan és körültekintően járjunk el, mert a kódbázis nem naprakész.
> 
> @Drelaky A nyelvet és az url-t jobban értem, ma adja hozzá ezt a jelzőt a nyelv vagy az url konfigurálásához, tapasztalatai szerint melyik forma a jobb az Ön számára? add paraméter a teljes eredeti URL cseréjéhez o csak string a régió megadásához hogyan ES_en , hu_HU. És ami a renderelés hibáját illeti, ennek a könyvtárnak van renderelési hibája? ez a hiba a facebook konzoljában az utolsó megjegyzésekben vagy más?
> 
> Első opció <ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' }" [ngxFacebookMessengerOptions]="{ page_id: 'YOUR_PAGE_ID' , language : 'Es_en' }">
> 
> Vagy <ngx-facebook-messenger [fbInitParams]="{ xfbml: true, version: 'v17.0' , language : 'Es_en' }" [ngxFacebookMessengerOptions]="{ page_id: 'YOUR_PAGE_ID' , url : 'YOUR_NEW_URL_SDK' ">

first option is good. And please add logged_in_greeting message and logged_out_greeting message params.

Render problem: yes this library has some kind of rendering problem because it throws an error the first time and then it loads for a long time.... After that it disappears it generates itself again and then it starts to work fine.

**Comment by SkyZeroZx** [comment]
@Drelaky 

About the options today add to the library 

About "render problem" it's a curious problem because it's error of facebook 
First the error in the console is by the official plugin currently running in your page or other page what inject the JS of Oficial SDK JS throw the same error always . Then this error not relations when the render
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/803ed759-d31b-4adf-8cd3-1d62c8fdb319)

About of the "real render problem" is by SDK Facebook not correctly detect when real attach in the DOM the plugin when emit the event **CUSTOMER CHAT LOAD**
Evidence of code
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/81e8c72f-e1dc-432d-8c3a-558c60011e84)
Then today investigate how fixed if is possible my idea it's detectec if attach the property correspondent in the DOM use a RxJS with timer and running out ngZone for better performance .

Edit : the solutions it's use mutationobserver for listening changes in the DOM

**Comment by SkyZeroZx** [comment]
@Drelaky 

I publish the **version 1.1.0** of the library and fixed the error of render , i created my own implementation for listening when load facebook messenger plugin with mutation observer.

Adicionally and the params configurable in NgxFacebookMessenger Options of language and greeting
And Fixed documentation about of CSS configurable 

![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/804c8d83-893c-42d9-a5fd-3cd6b907f27b)
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/337918b6-a7f0-421d-b69c-d13505c53bb5)

**Comment by Drelaky** [comment]
Ohm plsease check my web: https://ligetnails.hu/

my configuration:
html:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/21bf55ca-620a-491b-9f3c-130f7b66ea97)

ts:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/24fc7c24-dafb-43a5-9e2e-85f0f81459ab)


For some reason it still assigns the chat window incorrectly. Should I use a separate nxjs?  But then what does debounceTime in the module do?

**Comment by Drelaky** [comment]
Also a problem is that when you change the 'icon' to say icon text or text and click on it in the messenger then again something doesn't work right. However, once you have clicked and loaded the 'logo' normally you can't edit it... And if I change the color of the button, it sets itself fine at first, but for some reason it regenerates itself and goes back to blue.

**Comment by Drelaky** [comment]
And i see the html:

If first loaded element is your module. Good settings.
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/200018ab-194b-46f3-a3a6-529ca7f19d4b)

if i clicked element. (DOM). It will appear in the regular facebook element. And it doesn't apply what we set. Enter only the language and the welcome and departure texts
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/39622eb6-161e-4ff0-9cee-2ec12556e470)

When the facebook Module is loaded:
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/53569746/127c503d-679d-4e32-bc8d-e2c73d1499f5)


So I don't know how to set this up perfectly. Do you have a solution for this. The reason why the ordering is buggy is because the factory messenger module for facebook doesn't exist in the module yet for some reason. However, when you click it it loads. This is why it doesn't set things up normally for some reason. I'm thinking here when it should just show a plain text and loads the factory icon.

**Comment by SkyZeroZx** [comment]
> Also a problem is that when you change the 'icon' to say icon text or text and click on it in the messenger then again something doesn't work right. However, once you have clicked and loaded the 'logo' normally you can't edit it... And if I change the color of the button, it sets itself fine at first, but for some reason it regenerates itself and goes back to blue.

@Drelaky 

The configuration of aparience if it's button with text or other logo of messenger plugin should be configure in the oficial plugin facebook in your Bussiness Account of Facebook , because the library is configurable with the same styles and customization.
Reference : 
The oficial documentation say is more recommend configure Using Facebook Page settings setup tool
And seems imposible configure the style of button with HTML Atributtes 
https://developers.facebook.com/docs/messenger-platform/discovery/facebook-chat-plugin/customization

About other regenerate and change with the blue default color it's the same configuration no it's configure in your Bussiness Account possible but if it's possible configure with the library , today add this option of color facebook plugin 

I propose add in similar to lazy option
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/358fcc4b-de21-49de-a243-cd9e3218cd35)

**Comment by SkyZeroZx** [comment]
> And i see the html:
> 
> If first loaded element is your module. Good settings. ![image](https://user-images.githubusercontent.com/53569746/278878876-200018ab-194b-46f3-a3a6-529ca7f19d4b.png)
> 
> if i clicked element. (DOM). It will appear in the regular facebook element. And it doesn't apply what we set. Enter only the language and the welcome and departure texts ![image](https://user-images.githubusercontent.com/53569746/278878899-39622eb6-161e-4ff0-9cee-2ec12556e470.png)
> 
> When the facebook Module is loaded: ![image](https://user-images.githubusercontent.com/53569746/278879119-127c503d-679d-4e32-bc8d-e2c73d1499f5.png)
> 
> So I don't know how to set this up perfectly. Do you have a solution for this. The reason why the ordering is buggy is because the factory messenger module for facebook doesn't exist in the module yet for some reason. However, when you click it it loads. This is why it doesn't set things up normally for some reason. I'm thinking here when it should just show a plain text and loads the factory icon.

About this , i understand your want by default load on init component the oficial plugin ?

It is possible but as I indicated above it will kill the core web vitals

If you require it, it can be added as a flag to start directly.

I propose the following way by default lazy is true and if required it is false
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/be32e72d-2908-4296-afbb-a275b9a558c3)

**Comment by SkyZeroZx** [comment]
> Ohm plsease check my web: https://ligetnails.hu/
> 
> my configuration: html: ![image](https://user-images.githubusercontent.com/53569746/278877788-21bf55ca-620a-491b-9f3c-130f7b66ea97.png)
> 
> ts: ![image](https://user-images.githubusercontent.com/53569746/278877797-24fc7c24-dafb-43a5-9e2e-85f0f81459ab.png)
> 
> For some reason it still assigns the chat window incorrectly. Should I use a separate nxjs? But then what does debounceTime in the module do?

The debounceTime was created because there was previously a delay in rendering the official Facebook component, in theory with the update with version 1.1.0 it should not be necessary but I still left it

**Comment by SkyZeroZx** [comment]
@Drelaky 
Today release a version **1.2.0** of library add this changes 
- Lazy parameter for eager or not load oficial pluggin of facebok , default is true for better performance 
- theme_color default null for take default configuration of setup plugin , or configure in HTML attribute
![image](https://github.com/SkyZeroZx/ngx-facebook-messenger/assets/73321943/2f2f25f7-cefd-4042-8b10-55dc2abcf5a1)

Tell if exist of error or feature , please open other issue for close this
